version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/test-db
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
