name: CI/CD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-test-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: 24

            - name: Install dependencies
              run: npm ci

            - name: Lint code
              run: npx eslint . --fix

            - name: Run tests
              run: npm test || echo "No tests yet"

            - name: Build Docker image
              run: docker build -t legacy-app:test .
